import nodemailer from 'nodemailer'

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { assessment, recipientEmail, pdfBase64 } = req.body
  if (!assessment || !recipientEmail) return res.status(400).json({ error: 'Missing required fields' })

  const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.EMAIL_PORT || '587'),
  secure: false,            // STARTTLS on port 587
  auth: { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASS },
})

  const { patient_name, assessor_name, assessor_email, assessment_date, product, client } = assessment
  const filename = `BHS_Assessment_${(patient_name||'Patient').replace(/\s+/g,'_')}_${(assessment_date||'').replace(/\//g,'-')}.pdf`

  const htmlBody = `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  body{font-family:Arial,sans-serif;color:#1e293b;margin:0;padding:0;background:#f8fafc}
  .container{max-width:600px;margin:0 auto;background:white}
  .header{background:#2B3A8F;padding:0}
  .header-inner{padding:24px 32px}
  .header h1{color:white;margin:0;font-size:20px}
  .header p{color:#a5b4fc;margin:4px 0 0;font-size:12px}
  .accent{height:4px;background:linear-gradient(to right,#2B3A8F,#00B4D8,#3DB54A)}
  .body{padding:28px 32px}
  .info-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:16px 0}
  .info-card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px}
  .info-card h3{margin:0 0 8px;font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#64748b}
  .info-row{display:flex;justify-content:space-between;margin:3px 0;font-size:12px}
  .label{color:#64748b}.value{font-weight:600;color:#1e293b}
  .badge{display:inline-block;padding:3px 10px;border-radius:99px;font-size:11px;font-weight:600;margin-right:6px}
  .badge-navy{background:#e8ebf9;color:#2B3A8F}
  .badge-green{background:#e8f8ea;color:#2a9e36}
  .footer{background:#f1f5f9;border-top:1px solid #e2e8f0;padding:14px 32px;font-size:10px;color:#94a3b8;display:flex;justify-content:space-between;align-items:center}
</style></head><body>
<div class="container">
  <div class="header">
    <div class="header-inner">
      <h1>Bridgeway Healthcare</h1>
      <p>Clinical Assessment Report — ${product || 'Assessment'}</p>
    </div>
    <div class="accent"></div>
  </div>
  <div class="body">
    <p style="color:#64748b;font-size:13px;margin-top:0">
      Dear ${assessor_name},<br><br>
      Please find attached the clinical assessment report for <strong>${patient_name}</strong> 
      conducted on <strong>${assessment_date}</strong> for <strong>${client || 'client'}</strong>.
    </p>
    <div class="info-grid">
      <div class="info-card">
        <h3>Patient Details</h3>
        <div class="info-row"><span class="label">Name</span><span class="value">${patient_name}</span></div>
        <div class="info-row"><span class="label">Age</span><span class="value">${assessment.patient_age || '—'}</span></div>
        <div class="info-row"><span class="label">Height</span><span class="value">${assessment.patient_height || '—'}</span></div>
        <div class="info-row"><span class="label">Product</span><span class="value">${product || '—'}</span></div>
      </div>
      <div class="info-card">
        <h3>Assessor & Client</h3>
        <div class="info-row"><span class="label">Assessor</span><span class="value">${assessor_name}</span></div>
        <div class="info-row"><span class="label">Email</span><span class="value">${assessor_email}</span></div>
        <div class="info-row"><span class="label">Date</span><span class="value">${assessment_date}</span></div>
        <div class="info-row"><span class="label">Client</span><span class="value">${client || '—'}</span></div>
      </div>
    </div>
    <div style="margin:16px 0">
      ${assessment.wheelchair_data ? '<span class="badge badge-navy">✓ Wheelchair & Seating</span>' : ''}
      ${assessment.standing_data ? '<span class="badge badge-green">✓ Standing & Walking</span>' : ''}
    </div>
    <p style="font-size:12px;color:#475569">The full PDF report is attached. Please retain in the patient file.</p>
    <hr style="border:none;border-top:1px solid #e2e8f0;margin:20px 0">
    <p style="font-size:10px;color:#94a3b8;margin:0">Auto-generated by Bridgeway Healthcare Assessment Tool. Do not reply.</p>
  </div>
  <div class="footer">
    <span>Bridgeway Healthcare — Confidential Clinical Document</span>
    <span>${new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</span>
  </div>
</div></body></html>`

  const toList = [recipientEmail]
  if (assessor_email && assessor_email !== recipientEmail) toList.push(assessor_email)
  const adminEmail = process.env.ADMIN_EMAIL

  try {
    await transporter.verify()
    await transporter.sendMail({
      from: `"Bridgeway Healthcare" <${process.env.EMAIL_USER}>`,
      to: toList.join(', '),
      cc: adminEmail || undefined,
      subject: `BHS Assessment Report — ${patient_name} · ${product || ''} · ${client || ''} (${assessment_date})`,
      html: htmlBody,
      attachments: pdfBase64 ? [{ filename, content: pdfBase64, encoding: 'base64', contentType: 'application/pdf' }] : [],
    })
    return res.status(200).json({ success: true })
  } catch (error) {
    console.error('Email error:', error)
    return res.status(500).json({ error: 'Failed to send email', details: error.message })
  }
}
